name: docs_pages_workflow
 
# execute this workflow automatically when a we push to master branch
on:
  push:
    branches: [ docs ]
 
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.3/pandoc-3.3-1-amd64.deb
          sudo dpkg -i pandoc-3.3-1-amd64.deb
      - name: Install Sphinx dependencies
        run: |
          pip install -r requirements-docs.txt
      - name: Install PARC requirements
        run: |
          pip install -r requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build docs _build  -E -a
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/docs' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true